version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - LOG_LEVEL=debug
      # Fallback environment variables in case .env is missing
      - WEAVIATE_URL=${WEAVIATE_URL:-}
      - WEAVIATE_API_KEY=${WEAVIATE_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    networks:
      - hr-network
    healthcheck:
      # Simpler healthcheck that uses our explicit test endpoint
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/test', res => { if (res.statusCode !== 200) { process.exit(1) } else { process.exit(0) } })"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  frontend:
    build:
      context: ./platform
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - hr-network
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:3000
      - NODE_ENV=${NODE_ENV:-development}

networks:
  hr-network:
    driver: bridge