version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - LOG_LEVEL=debug
    networks:
      - hr-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/test"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./platform
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - hr-network
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:3000
      - NODE_ENV=${NODE_ENV:-development}

networks:
  hr-network:
    driver: bridge